# Motion sensors configuration
#
# Each sensor is tied to a device
# - enocean:name -> Retrieve from enocean sensor (enocean.py)
#
# Sensors can have optional attributes:
# - outside=true: Tell if the sensor is located outside (used for not triggering alarm)
# - rabbit=name: Tell which rabbit the sensor is placed next to (several sensors can have the same rabbit), for use in scenarios and notifications

[RoomOne]
device=enocean:sensorone
rabbit=rabbitone

[Outside]
device=enocean:sensortwo
outside=true
